Storybook usage guideliens
mondaycom/vibe-storybook-components pull request #23
Opened 2023-10-02 14:48 UTC by talkor

Used the new convention of storybook 7, let me know what you guys think.
Once we're ok with this let's continue documenting the rest of the components here

2023-10-02 14:48 UTC, talkor commented on src/components/usage-guidelines/usage-guidelines.jsx
Personally I like PascalCase for components' filenames

2023-10-02 14:49 UTC, talkor commented on src/components/usage-guidelines/usage-guidelines.jsx
> +import './usage-guidelines.scss';
File name was incorrect (doesn't match the component's name)

2023-10-02 14:50 UTC, talkor commented on .storybook/main.ts
> +  stories: ['../src/**/*.mdx', '../src/**/*.stories.tsx', '../storybook/**/*.stories.mdx'],
Stories should now be in `*.stories.[tsx|js]` format and mdx files should not include `.stories`

2023-10-02 14:51 UTC, talkor commented on src/components/usage-guidelines/README.md
> -# UsageGuideline
Added this documentation to the mdx file

2023-10-03 14:54 UTC, SergeyRoyt requested changes
Proposed some changes here https://github.com/mondaycom/vibe-storybook-components/pull/24
Please, tell me what you think

2023-10-04 09:59 UTC, SergeyRoyt approved these changes

2023-10-04 10:22 UTC, merged