feat: Migrate < Link />, < StoryDescription /> to ts
mondaycom/vibe-storybook-components pull request #83
Opened 2023-10-17 06:42 UTC by Dhoni77

- Migrate Link and StoryDescription components to ts

2023-10-17 11:28 UTC, SergeyRoyt commented on src/components/link/link.tsx
> +  className: string;
```suggestion
  className?: string;
```

2023-10-17 11:29 UTC, SergeyRoyt commented on src/components/link/link.tsx
> +const Link: FC<LinkProps> = ({ children, href, size = Size.MEDIUM, withoutSpacing = false, className }) => (
```suggestion
const Link: FC<LinkProps> & { sizes?: typeof Size } = ({ children, href, size = Size.MEDIUM, withoutSpacing = false, className }) => (
```

2023-10-17 11:31 UTC, SergeyRoyt commented on src/components/link/link.tsx
> +export default Link;
```suggestion
export default withStaticProps(Link, { sizes: Size } );
```

So we'd be able to use it like this e.g. in other packages
`<Link size={Link.sizes.MEDIUM}`

Same as we do in `Tip`

2023-10-17 11:32 UTC, SergeyRoyt commented on src/components/link/LinkConstants.ts
> +export enum Size {
```suggestion
export enum LinkSize {
```

2023-10-17 11:33 UTC, SergeyRoyt commented on src/components/story-description/story-description.tsx
> +  description?: string | ElementContent;
```suggestion
  description?: ElementContent;
```
Already contains string

2023-10-17 11:34 UTC, SergeyRoyt commented on src/components/story-description/story-description.tsx
> +  align?: FlexAlign;
Let's also add this enum to static props, so we'd be able to reference it like this `StoryDescription.align.START`

2023-10-17 11:35 UTC, SergeyRoyt commented on src/components/story-description/story-description.tsx
> +  headerJustify?: FlexJustify;
Let's add this enums to static too

2023-10-17 11:35 UTC, SergeyRoyt commented on src/components/story-description/story-description.tsx
> +  justify?: FlexJustify;
Can also be a static prop

2023-10-17 11:37 UTC, SergeyRoyt commented on src/components/story-description/story-description.tsx
> +  headerStyle: Record<string, unknown>;
```suggestion
  headerStyle: React.CSSProperties;
```

2023-10-17 11:37 UTC, SergeyRoyt commented on src/components/link/LinkConstants.ts
> +};
lint

2023-10-17 11:37 UTC, SergeyRoyt requested changes
Nice!
Let's just fix a few notes and make all checks green
Update master and merge from it to fix the build issues

2023-10-18 13:21 UTC, SergeyRoyt commented
@Dhoni77  there are still some typescript issues to fix

2023-10-19 15:51 UTC, Dhoni77 commented
> @Dhoni77 there are still some typescript issues to fix

Hi @SergeyRoyt I ran lint I did not give any type errors

2023-10-22 08:42 UTC, SergeyRoyt commented
> > @Dhoni77 there are still some typescript issues to fix
> 
> Hi @SergeyRoyt I ran lint I did not give any type errors

@Dhoni77 Yeah, but it's not a lint issue, it's a TS error
![image](https://github.com/mondaycom/vibe-storybook-components/assets/104433616/91bc8844-bd95-415c-b39e-9cf8ffbaa199)
You have access to view details of these checks I ran, right?

2023-10-22 09:16 UTC, Dhoni77 commented
> > > @Dhoni77 there are still some typescript issues to fix
> > 
> > 
> > Hi @SergeyRoyt I ran lint I did not give any type errors
> 
> @Dhoni77 Yeah, but it's not a lint issue, it's a TS error ![image](https://user-images.githubusercontent.com/104433616/277154211-91bc8844-bd95-415c-b39e-9cf8ffbaa199.png) You have access to view details of these checks I ran, right?

Ok got it will fix this👍

2023-10-22 09:29 UTC, Dhoni77 commented
Hi @SergeyRoyt ,

In the `<Link />`  component should I make the href as optional property or send an empty string '' to `<Link />` in `<DeprecatedWarning />` to get rid of this typeerror.
Which one is expected ?

2023-10-23 08:23 UTC, SergeyRoyt commented
> Hi @SergeyRoyt ,
> 
> In the `<Link />` component should I make the href as optional property or send an empty string '' to `<Link />` in `<DeprecatedWarning />` to get rid of this typeerror. Which one is expected ?

Hey, @Dhoni77 !
Let's probably make `alternativeLink` in the `DeprecatedWarning` not optional - that will fix the issue and makes sense

2023-10-23 10:30 UTC, Dhoni77 commented
cc @SergeyRoyt

2023-10-23 11:16 UTC, SergeyRoyt requested changes
Not sure where the lint issues are coming from, but, please, let's fix them before merge

2023-10-23 11:18 UTC, SergeyRoyt approved these changes
Nvm, will fix lint by myself
Thanks a lot!

2023-10-23 11:18 UTC, merged