docs: create basic story for < ComponentDescription />, < UnstyledList /> + < UnstyledListItem />
mondaycom/vibe-storybook-components pull request #93
Opened 2023-10-20 10:58 UTC by Dhoni77

Closes #89

- Added stories for < ComponentDescription />, < UnstyledList /> + < UnstyledListItem />

2023-10-22 09:10 UTC, SergeyRoyt commented on src/components/unstyled-list/__stories__/unstyled-list.mdx
> +This component can be used as a replacement for `ul`.
```suggestion
This component can be used as a replacement for `ul` and it's child component `UnstyledListItem` can be used as a replacement for `li`.
```

2023-10-22 09:11 UTC, SergeyRoyt requested changes
One small note, the rest is great!

2023-10-22 09:15 UTC, Dhoni77 commented
cc @SergeyRoyt

2023-10-23 08:26 UTC, SergeyRoyt approved these changes
Great! Thank you!! 🙏

2023-10-23 08:26 UTC, merged