docs: add story for < TokenTable />
mondaycom/vibe-storybook-components pull request #95
Opened 2023-10-20 13:10 UTC by Dhoni77

Closes #90

Added story for `<TokenTable/>` component.

2023-10-20 13:11 UTC, Dhoni77 commented
cc @SergeyRoyt

2023-10-22 08:35 UTC, SergeyRoyt commented on src/components/token-table/__stories__/token-table.mdx
> +TokenTable component is used to display a table with rows and columns.
```suggestion
TokenTable component is used to display a table with rows and columns and is designed to display tokens values. 
```

2023-10-22 08:36 UTC, SergeyRoyt commented on src/components/token-table/__stories__/token-table.stories.tsx
> +    theadData: ['Column A', 'Column B'],
```suggestion
    theadData: ['Token', 'Value'],
```

We are just mostly using it to display smth like this
![image](https://github.com/mondaycom/vibe-storybook-components/assets/104433616/b087d4e5-8d7e-4dd0-a302-9179b456c042)

2023-10-22 08:38 UTC, SergeyRoyt commented on src/components/token-table/__stories__/token-table.stories.tsx
> +      { id: '2', items: ['value 2', 'value 4'] },
```suggestion
      { id: '1', items: ['--token-1', '#111'] },
      { id: '2', items: ['--token-2', '#222'] },
```

2023-10-22 08:39 UTC, SergeyRoyt requested changes
Nice!
Let's just adjust example a little bit to be more specific to out use case

2023-10-23 08:25 UTC, SergeyRoyt approved these changes
Amazing! Thanks a lot!

2023-10-23 08:25 UTC, merged